# Generated by Django 3.0.2 on 2020-08-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0005_auto_20200817_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
